# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Kim
email: michaelkim314@gmail.com
description:  wwwwwwwwwwwwwwwww wwwwwwwwwwwwwwwwwwwwww wwwwwwwwwwwwwwww
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

repo: http://github.com/lenkagamine/lenkagamine.github.io

author:
  name: Michael Kim
  bio: "Welcome to my website test test"
  photo: "https://avatars0.githubusercontent.com/u/8509052"
  email: michaelkim314@gmail.com
  github: lenkagamine
  linkedin: michaelkim314

# Build settings
markdown: kramdown
